### ISSUE TITLE
Dark theme Epic

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly#4826]
Epic to track creation & implementation of dark theme in PatternFly

### PatternFly implementation
  - [x] https://github.com/patternfly/patternfly/pull/4654
  - [x] https://github.com/patternfly/patternfly/pull/4761
  - [x] https://github.com/patternfly/patternfly/issues/4790
  - [x] https://github.com/patternfly/patternfly/issues/4749
  - [x] https://github.com/patternfly/patternfly/issues/4700
  - [x] https://github.com/patternfly/patternfly/pull/4799
  - [x] https://github.com/patternfly/patternfly/issues/3833
  - [x] https://github.com/patternfly/patternfly/issues/4771

  ### Docs
  - [x] Core: patternfly/patternfly-org#2959
  - [x] React: https://github.com/patternfly/patternfly-react/issues/7278

  ### Integration demo app
  - [x] https://github.com/patternfly/patternfly-react/issues/6956
  - [x] https://github.com/patternfly/patternfly-react/issues/7223

  ### Extensions:

  #### Quick starts
  - [x] https://github.com/patternfly/patternfly-quickstarts/issues/82
  - [ ] https://github.com/patternfly/patternfly-quickstarts/issues/155

  #### Charts
  - [x] Core: https://github.com/patternfly/patternfly/issues/4804
  - [x] React: https://github.com/patternfly/patternfly-react/issues/7188

  #### Topology ✅
  - [x] https://github.com/patternfly/patternfly-react/issues/7181

  #### Catalog view extension ✅ 
  - [x] https://github.com/patternfly/patternfly-react/issues/7105
  - [x] https://github.com/patternfly/patternfly-react/issues/7174

---

### Design ✅ 
  - [x] https://github.com/patternfly/patternfly-design/issues/754

  ### Core POC ✅ 
  - [x] https://github.com/patternfly/patternfly/issues/3297
  - [x] https://github.com/patternfly/patternfly/pull/3298
  - [x] https://github.com/patternfly/patternfly/pull/3686
  - [x] https://github.com/patternfly/patternfly/pull/4203

  ### OpenShift POC ✅ 
  - [x] https://github.com/patternfly/patternfly/issues/4565
  - [Evaluation feedback sheet](https://docs.google.com/spreadsheets/d/1fBCPPb4Z1sqUDKgQkpueGe8VQZo4pBUA9PV4vnFCnDw/edit#gid=0)

---

## Design: ✅ 
  - [x] https://github.com/patternfly/patternfly-design/issues/754 (Zenhub epic)
<details>
<summary>Design issues:</summary>

- [x] https://github.com/patternfly/patternfly-design/issues/1016
- [x] https://github.com/patternfly/patternfly-design/issues/1008
- [x] https://github.com/patternfly/patternfly-design/issues/1014
- [x] https://github.com/patternfly/patternfly-design/issues/980
- [x] https://github.com/patternfly/patternfly-design/issues/1005
- [x] https://github.com/patternfly/patternfly-design/issues/941
- [x] https://github.com/patternfly/patternfly-design/issues/940
- [x] https://github.com/patternfly/patternfly-design/issues/948
- [x] https://github.com/patternfly/patternfly-design/issues/880
- [x] https://github.com/patternfly/patternfly-design/issues/954
- [x] https://github.com/patternfly/patternfly-design/issues/939
- [x] https://github.com/patternfly/patternfly-design/issues/868
- [x] https://github.com/patternfly/patternfly-design/issues/959
- [x] https://github.com/patternfly/patternfly-design/issues/953
- [x] https://github.com/patternfly/patternfly-design/issues/938
- [x] https://github.com/patternfly/patternfly-design/issues/942
- [x] https://github.com/patternfly/patternfly-design/issues/946
- [x] https://github.com/patternfly/patternfly-design/issues/947
- [x] https://github.com/patternfly/patternfly/issues/3211

</details>

**Comment by septatrix** [comment]
What's the current state/progress here? (just a ping as this is a tracking issue so not really stale)

**Comment by septatrix** [comment]
Still relevant

**Comment by jessiehuff** [comment]
We'd like to, but we think that catalog view needs a design review first. It's been hard for the designers to give a proper design review until a demo can be given to them with all of the comments working together.
