### ISSUE TITLE
Consume tokens in: Panel, Drawer, Sidebar, Tab content

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5711]
[Figma design for drawer](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A15&mode=design&t=doZDRUaxE4vsn5dD-1)

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/pull/6160
- [ ] https://github.com/patternfly/patternfly/pull/6183
- [ ] https://github.com/patternfly/patternfly/pull/6178
- [x] #6161
```
