### ISSUE TITLE
Consume tokens: Menu, Menu Toggle, Dropdown, Select, Overflow Menu (exclude deprecated Context Selector, Application Launcher, Options menu

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5718]
[Figma design for menus](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A16&mode=design&t=doZDRUaxE4vsn5dD-1)

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/6162
- [ ] https://github.com/patternfly/patternfly/issues/6163
- [ ] https://github.com/patternfly/patternfly/issues/6164
- [ ] https://github.com/patternfly/patternfly/issues/6165
- [ ] https://github.com/patternfly/patternfly/issues/6166
```

**Comment by nicolethoen** [comment]
I'm not sure that we need to tokenize the deprecated context selector, application launcher, or options menu.

since we will be delivering a classic theme, these deprecated components will be able to coexist untouched alongside the classic themed components. 

And it will motivate people to migrate away from using deprecated components. They won't be blocked from adopting v6, but they will be blocked from adopting the Penta theme until they remove these deprecated components.

**Comment by srambach** [comment]
All issues closed for v6
