### ISSUE TITLE
Consume tokens: Avatar, Brand, Background image, Backdrop, Divider, Truncate, Icon

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5724]
[Figma design for avatar](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A19&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for brand](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=14%3A165&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for divider](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A14&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for icons](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A28&mode=design&t=doZDRUaxE4vsn5dD-1)
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/6120
- [ ] https://github.com/patternfly/patternfly/issues/6126
- [ ] https://github.com/patternfly/patternfly/issues/6145
- [ ] https://github.com/patternfly/patternfly/issues/6137
- [ ] https://github.com/patternfly/patternfly/issues/6136
- [ ] https://github.com/patternfly/patternfly/issues/6143
- [ ] https://github.com/patternfly/patternfly/issues/6179
```

**Comment by mcoker** [comment]
All of the tasks are complete!
