### ISSUE TITLE
Consume tokens: Switch, Slider, Spinner, Skeleton

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5738]
[Figma design for slider](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A45&mode=design&t=boxqVg1hn5hO0weV-1)

[Figma design for skeleton and spinner](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A44&mode=design&t=boxqVg1hn5hO0weV-1)

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/pull/6153
- [ ] https://github.com/patternfly/patternfly/pull/6157
- [ ] https://github.com/patternfly/patternfly/pull/6154
- [ ] https://github.com/patternfly/patternfly/pull/6158
```
