### ISSUE TITLE
Consume tokens: Banner, Pagination, Skip to Content, and Back to Top

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5743]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/6082
- [ ] https://github.com/patternfly/patternfly/issues/6083
- [ ] https://github.com/patternfly/patternfly/issues/6088
- [ ] https://github.com/patternfly/patternfly/issues/6084
```

[Figma design for banner](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A8&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for pagination](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A37&mode=design&t=doZDRUaxE4vsn5dD-1)

[Figma design for back to top](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=3%3A17&mode=design&t=doZDRUaxE4vsn5dD-1)
