### ISSUE TITLE
Epic: Implement RTL support in core

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5757]
**Describe the feature**
Users would like PatternFly to support right to left (RTL) languages. CSS provides support for this via logical properties like padding-inline-start rather than directional properties like padding-left.

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/5758
- [ ] https://github.com/patternfly/patternfly/issues/5759
- [ ] https://github.com/patternfly/patternfly/issues/5760
- [ ] https://github.com/patternfly/patternfly/issues/5761
- [ ] https://github.com/patternfly/patternfly/issues/5762
- [ ] https://github.com/patternfly/patternfly/issues/5811
- [ ] https://github.com/patternfly/patternfly/issues/5814
- [ ] https://github.com/patternfly/patternfly/issues/5815
- [ ] https://github.com/patternfly/patternfly/issues/5816
- [ ] https://github.com/patternfly/patternfly/issues/5817
- [ ] https://github.com/patternfly/patternfly/issues/5818
- [ ] https://github.com/patternfly/patternfly/issues/5819
- [ ] https://github.com/patternfly/patternfly/issues/5820
- [ ] https://github.com/patternfly/patternfly/issues/5821
- [ ] https://github.com/patternfly/patternfly/issues/5822
- [ ] https://github.com/patternfly/patternfly/issues/5763
- [ ] https://github.com/patternfly/patternfly/issues/5823
- [ ] https://github.com/patternfly/patternfly/issues/5824
- [ ] https://github.com/patternfly/patternfly/issues/5825
- [ ] https://github.com/patternfly/patternfly/issues/5826
- [ ] https://github.com/patternfly/patternfly/issues/5827
- [ ] https://github.com/patternfly/patternfly/issues/5828
- [ ] https://github.com/patternfly/patternfly/issues/5829
- [ ] https://github.com/patternfly/patternfly/issues/5830
- [ ] https://github.com/patternfly/patternfly/issues/5831
- [ ] https://github.com/patternfly/patternfly/issues/5832
- [ ] https://github.com/patternfly/patternfly/issues/5833
- [ ] https://github.com/patternfly/patternfly/issues/5834
- [ ] https://github.com/patternfly/patternfly/issues/5835
- [ ] https://github.com/patternfly/patternfly/issues/5836
- [ ] https://github.com/patternfly/patternfly/issues/5837
- [ ] https://github.com/patternfly/patternfly/issues/5838
- [ ] https://github.com/patternfly/patternfly/issues/5839
- [ ] https://github.com/patternfly/patternfly/issues/5840
```

**Comment by mcoker** [comment]
Great job team! Shout out to @andrew-ronaldson @mattnolting @srambach @tobiastal @thatblindgeye @wise-king-sullyman for getting this done!
