### ISSUE TITLE
set up style dictionary repo and determine delivery method

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#5781]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/design-tokens/issues/1
- [ ] https://github.com/patternfly/design-tokens/issues/2
- [ ] https://github.com/patternfly/design-tokens/issues/3
```

**Comment by srambach** [comment]
Various improvements are in issues on https://github.com/patternfly/design-tokens/issues but this issue can be considered done.
