### ISSUE TITLE
Utilities - apply tokens

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6315]
Utility classes need to have tokens applied and the sass variables removed.

```[tasklist]
### Tasks
- [x] Accessibility utilities
- [x] Alignment utilities
- [x] Background color utilities
- [x] Box shadow utilities
- [x] Display utilities
- [x] Flex utilities
- [x] Float utilities
- [x] Sizing utilities
- [x] Spacing utilities
- [ ] https://github.com/patternfly/patternfly/issues/6486
- [ ] https://github.com/patternfly/patternfly/issues/6491
```

Note that some utilities will probably change to shift to semantic names rather than palette/base names, e.g. background and text color utilties.

Related issue: https://github.com/patternfly/patternfly/issues/6273

**Comment by srambach** [comment]
Closed by #6487 , #6492, #6400
