### ISSUE TITLE
Epic - tokens and variables

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6386]
This epic captures issues related cleaning up tokens and variables. 

```[tasklist]
### Tokens and variables
- [ ] https://github.com/patternfly/patternfly/issues/6185
- [ ] https://github.com/patternfly/patternfly/issues/6312
- [ ] https://github.com/patternfly/patternfly/issues/6105 Depends on https://github.com/patternfly/design-tokens/issues/9)
- [ ] https://github.com/patternfly/patternfly/issues/6305
- [ ] https://github.com/patternfly/patternfly/issues/6363
- [ ] https://github.com/patternfly/patternfly/issues/6292
- [ ] https://github.com/patternfly/design-tokens/issues/40
- [ ] https://github.com/patternfly/patternfly/issues/6295
- [ ] https://github.com/patternfly/patternfly/issues/6123
- [ ] https://github.com/patternfly/patternfly/issues/6362
- [ ] https://github.com/patternfly/patternfly/issues/6255
- [ ] https://github.com/patternfly/patternfly/issues/6389
```

**Comment by srambach** [comment]
Close because it's no longer needed for organization purposes
