### ISSUE TITLE
Epic - Update core demos for Penta

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6387]
This epic captures core changes needed to update demos for Penta

**Reminder: create issues if any React follow up is needed**

```[tasklist]
### Update demos
- [ ] https://github.com/patternfly/patternfly/issues/5346
- [ ] https://github.com/patternfly/patternfly/issues/6207
- [ ] https://github.com/patternfly/patternfly/issues/5744
- [ ] https://github.com/patternfly/patternfly/issues/6232
- [ ] https://github.com/patternfly/patternfly/issues/6249
```

**Comment by mcoker** [comment]
Closing the epic, most of the items are complete.
