### ISSUE TITLE
Epic - Core refactor/follow-ups for Penta/V6

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6388]
This epic is for essential refactoring needed for V6.

**Reminder: Be sure to create React tasks as necessary**

```[tasklist]
### Miscellaneous
- [ ] https://github.com/patternfly/patternfly/issues/6300
- [ ] https://github.com/patternfly/patternfly/issues/6094
- [ ] https://github.com/patternfly/patternfly/issues/6314
- [ ] https://github.com/patternfly/patternfly/issues/6317
- [ ] https://github.com/patternfly/patternfly/issues/6234
- [ ] https://github.com/patternfly/patternfly/issues/6303
- [ ] https://github.com/patternfly/patternfly/issues/6320
- [ ] https://github.com/patternfly/patternfly/issues/6324
- [ ] https://github.com/patternfly/patternfly/issues/6238
- [ ] https://github.com/patternfly/patternfly/issues/6408
- [ ] https://github.com/patternfly/patternfly/issues/6388
```

**Comment by srambach** [comment]
Closing because it's no longer needed for tracking purposes
