### ISSUE TITLE
Epic - Implement animations on components

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6517]
**Describe the feature**
Following #6516, implement animation on components as defined by design. Documentation of animation design at TBD.

```[tasklist]
### Components with animation
- [ ] Toast alerts
- [ ] Clickable icons - notification badge (bell)
- [ ] Clickable icons - settings (gear/cog)
- [ ] Clickable icons - favoriting (star)
- [ ] Buttons (primary and secondary)
- [ ] Search input expandable button
- [ ] Navigation - expandable navigation items
- [ ] Navigation - hover/click
- [ ] Navigation - drilldown
- [ ] Menu item hover/click
- [ ] Menu panel open/close
- [ ] Menu toggle hover/click
```

**Comment by andrew-ronaldson** [comment]
Closing as duplicate of https://github.com/patternfly/pf-roadmap/issues/177
