### ISSUE TITLE
@import -> @use/@forward

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6518]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/6519
- [ ] https://github.com/patternfly/patternfly/issues/6520
- [ ] https://github.com/patternfly/patternfly/issues/6524
- [ ] https://github.com/patternfly/patternfly/issues/6535
```

**Comment by mcoker** [comment]
All tasks closed 🚀
