### ISSUE TITLE
Remove remaining Sass variables used in components

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6530]
**Describe the feature**
Remove Sass variables in favor of tokens, so that we can remove the global sass variables. **Use the closest available token; no refactoring or redesign for this.**

```[tasklist]
### Components
- [x] App launcher - remove global sass variables
- [x] Chip - remove global sass variables
- [x] Chip group - remove global sass variables
- [x] Context selector - remove global sass variables
- [x] Dropdown - remove global sass variables
- [x] Log viewer - remove global sass variables
- [x] Options menu - remove global sass variables
- [x] Select - remove global sass variables
- [x] `pf-t-light` and `pf-t-dark` mixins and placeholders - remove global sass variables
```

**Comment by kmcfaul** [comment]
All but log-viewer can be temporarily removed from the repo to correspond with the removal of react deprecated components.

**Comment by mcoker** [comment]
All tasks complete
