### ISSUE TITLE
Design review bugs: Beta components

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6822]
Clean up tasks for beta.

```[tasklist]
### Tasks
- [x] Modal title not using heading font
- [x] Drawer static/inline use primary not floating background
- [x] html demo “Drawer with jump links” to “Collapsed drawer with jump links”
- [x] Drawer. update the shadow to use a medium size (currently large in design & dev)
- [x] Add semantic spacers to action items/groups (core & design)
- [x] Inline edit. Update inline edit action groups to use new semantic gap spacers
```

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6825
